version: "3"

services:
    db:
        image: postgres:11.2-alpine

        hostname: db
        ports:
            - "5433:5432"
        env_file:
            - db-variables.env
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
    web:
        build: .
        links:
            - db
        command: >
            bash -c "sleep 1
            && python manage.py makemigrations
            && python manage.py migrate --settings=config.settings.develop
            && python manage.py runserver 0.0.0.0:8000 --settings=config.settings.develop"
        volumes:
            - .:/gestor_absencies
        ports:
            - "8000:8000"
        depends_on:
            - db