version: "3"

services:
    db:
        image: postgres
        hostname: db
        ports:
            - "5433:5432"
        environment:
            POSTGRES_DB: gestor_absencies_db
            POSTGRES_USER: gestor_absencies
    web:
        build: .
        links:
            - db
        command: >
            bash -c "python manage.py makemigrations
            && python manage.py migrate --settings=config.settings.develop
            && python manage.py runserver 0.0.0.0:8000 --settings=config.settings.develop"
        volumes:
            - .:/gestor_absencies
        ports:
            - "8000:8000"
        depends_on:
            - db