version: "3"

services:
    db:
        image: postgres:11.2-alpine
        hostname: db
        ports:
            - "5433:5432"
        env_file:
            - db-variables.env
        volumes:
             - ./postgres-data:/var/lib/postgresql/data 
    web:
        build: .
        command: ["bash", "wait-for-it.sh", "db:5432", "--", "bash",  "start-server.sh"]
        volumes:
            - .:/gestor_absencies
        ports:
            - "8000:8000"
        depends_on:
            - db
