# Generated by Django 2.1.7 on 2019-04-17 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_absencies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='somenergiaabsence',
            name='absence_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor_absencies.SomEnergiaAbsenceType', verbose_name='Absence Type'),
        ),
        migrations.AlterField(
            model_name='somenergiaabsence',
            name='worker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Worker'),
        ),
        migrations.AlterField(
            model_name='somenergiaabsencetype',
            name='max_duration',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10, verbose_name='Maximun Duration'),
        ),
        migrations.AlterField(
            model_name='somenergiaabsencetype',
            name='max_spend',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10, verbose_name='Maximun Computation'),
        ),
        migrations.AlterField(
            model_name='somenergiaabsencetype',
            name='min_duration',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10, verbose_name='Minimun Duration'),
        ),
        migrations.AlterField(
            model_name='somenergiaabsencetype',
            name='min_spend',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10, verbose_name='Minimun Computation'),
        ),
        migrations.AlterField(
            model_name='somenergiaabsencetype',
            name='required_notify',
            field=models.BooleanField(default=True, verbose_name='Required Notify'),
        ),
        migrations.AlterField(
            model_name='somenergiaabsencetype',
            name='spend_days',
            field=models.IntegerField(default=0, verbose_name='Computation days'),
        ),
        migrations.AlterField(
            model_name='somenergiaoccurrence',
            name='absence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor_absencies.SomEnergiaAbsence', verbose_name='Absence'),
        ),
        migrations.AlterField(
            model_name='somenergiaoccurrence',
            name='start_time',
            field=models.DateTimeField(help_text='Date when this occurrence end', verbose_name='Start time occurrence'),
        ),
        migrations.AlterField(
            model_name='team',
            name='min_worker',
            field=models.IntegerField(default=0, verbose_name='Minimun Workers'),
        ),
        migrations.AlterField(
            model_name='vacationpolicy',
            name='description',
            field=models.CharField(max_length=250, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='vacationpolicy',
            name='holidays',
            field=models.IntegerField(default=0, verbose_name='Holidays'),
        ),
        migrations.AlterField(
            model_name='vacationpolicy',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='category',
            field=models.CharField(default='', max_length=50, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='gender',
            field=models.CharField(default='', max_length=50, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='holidays',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10, verbose_name='Holidays'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='vacation_policy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestor_absencies.VacationPolicy', verbose_name='Vacation Policy'),
        ),
    ]
