# Generated by Django 2.1.7 on 2019-03-19 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_absencies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='somenergiaabsencetype',
            name='required_notify',
            field=models.BooleanField(default=True, verbose_name=''),
        ),
    ]
