# Generated by Django 2.1.7 on 2019-03-19 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_absencies', '0002_somenergiaabsencetype_required_notify'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='min_worker',
            field=models.IntegerField(default=0, verbose_name=''),
        ),
    ]
