# Generated by Django 2.1.7 on 2019-03-26 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_absencies', '0003_team_min_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='vacation_policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor_absencies.VacationPolicy', verbose_name=''),
        ),
    ]
