# Generated by Django 2.1.7 on 2019-06-10 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_absencies', '0003_auto_20190429_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='somenergiaabsencetype',
            name='color',
            field=models.CharField(default='#ffffff', max_length=7, verbose_name='Representation color'),
            preserve_default=False,
        ),
    ]
