# Generated by Django 2.1.7 on 2019-06-17 08:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_absencies', '0004_somenergiaabsencetype_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='somenergiaabsencetype',
            name='global_date',
            field=models.BooleanField(default=False, verbose_name='Global holidays'),
        ),
        migrations.AddField(
            model_name='worker',
            name='contract_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 17, 8, 38, 6, 206806), verbose_name='Start contract date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worker',
            name='working_week',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10, verbose_name='Work hours per week'),
        ),
    ]
