# Generated by Django 2.1.7 on 2019-06-17 12:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_absencies', '0005_auto_20190617_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='contract_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start contract date'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='working_week',
            field=models.IntegerField(default=0, verbose_name='Work hours per week'),
        ),
    ]
