# Generated by Django 2.1.7 on 2019-03-26 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_absencies', '0005_auto_20190326_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='vacation_policy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestor_absencies.VacationPolicy', verbose_name=''),
        ),
    ]
