# Generated by Django 2.1.7 on 2019-03-27 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_absencies', '0006_auto_20190326_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='somenergiaabsencetype',
            name='spend_days',
            field=models.IntegerField(default=0, verbose_name=''),
        ),
    ]
