# Generated by Django 2.1.7 on 2019-07-04 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_absencies', '0009_auto_20190701_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='base',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Date when object was deleted', null=True, verbose_name='Deleted At'),
        ),
    ]
