# Generated by Django 2.2.4 on 2020-03-02 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_absencies', '0010_base_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='email',
            field=models.EmailField(max_length=50, unique=True, verbose_name='email address'),
        ),
    ]
