# Generated by Django 2.2.4 on 2020-03-03 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_absencies', '0011_auto_20200302_1301'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worker',
            options={'ordering': ('email',)},
        ),
    ]
